sudo: required
services:
    - docker

script:
    - docker build -t randyyele/node2 .
    - docker images randyyele/node2

before_deploy:
  - docker login -u randyyele  -p Edvine_yele_26

deploy:
  provider: script
  script: docker push randyyele/node2
  on:
    branch: master
